version = 1

# STM32CubeMX-generated files are provided AS-IS, unless a license file is provided
# in the component's root directory
[[annotations]]
path = [
    "firmware/Core/**",
    "firmware/Drivers/STM32F1xx_HAL_Driver/**",
    "firmware/Drivers/CMSIS/Device/ST/STM32F1xx/Include/**",
    "firmware/STM32F103**",
    "firmware/startup**",
    "firmware/cmake/stm32cubemx/CMakeLists.txt",
    "firmware/Leany.ioc",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2016-2025 STMicroelectronics"
SPDX-License-Identifier = "MIT"

# STM32CubeMX-generated files are provided AS-IS, unless a license file is provided
# in the component's root directory
[[annotations]]
path = [
    "firmware/Drivers/STM32F1xx_HAL_Driver/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2016-2025 STMicroelectronics"
SPDX-License-Identifier = "BSD-3-Clause"

# FreeRTOS files contain the MIT licensing text
[[annotations]]
path = "firmware/Middlewares/Third_Party/FreeRTOS/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020 Amazon.com, Inc. or its affiliates.  All Rights Reserved."
SPDX-License-Identifier = "MIT"

# Git hooks are MIT-licenced
[[annotations]]
path = "scripts/git-hooks/*"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Gilles Henrard <contact@gilleshenrard.com>"
SPDX-License-Identifier = "MIT"

# gitconfig is MIT-licenced
[[annotations]]
path = ".gitconfig"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Gilles Henrard <contact@gilleshenrard.com>"
SPDX-License-Identifier = "MIT"

# Doxygen configuration file is licensed on MIT
[[annotations]]
path = "firmware/Doxyfile"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Gilles Henrard <contact@gilleshenrard.com>"
SPDX-License-Identifier = "MIT"

# All files within Middlewares/Third_Party/FreeRTOS/ are generated by STM32CubeMX
[[annotations]]
path = "firmware/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 STMicroelectronics"
SPDX-License-Identifier = "Apache-2.0"

# CMSIS files which contain Apache-2.0 licensing text
[[annotations]]
path = "firmware/Drivers/CMSIS/Include/cmsis_iccarm.h"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017-2018 IAR Systems"
SPDX-License-Identifier = "Apache-2.0"

# PCB files are CERN Open Hardware Permissive licensed
[[annotations]]
path = "pcb/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Gilles Henrard <contact@gilleshenrard.com>"
SPDX-License-Identifier = "CERN-OHL-P-2.0"

# KiCAD library files are licensed under Creative Commons
[[annotations]]
path = "pcb/leany_footprints.pretty/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 KiCAD"
SPDX-License-Identifier = "CC-BY-SA-4.0"

# Bosch Sensortec submodule is BSD-3-Clause licensed
[[annotations]]
path = "firmware/Middlewares/Third_Party/BMI270_SensorAPI/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Bosch Sensortec GmbH. All rights reserved."
SPDX-License-Identifier = "BSD-3-Clause"

#
# GrabCAD files do not come with an explicit license and are therefore to be considered as restricted
#

[[annotations]]
path = ["pcb/resources/3d-models/grabcad/Ignaz_Kevenaar/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Ignaz Kevenaar <https://grabcad.com/ignaz.kevenaar-1>"
SPDX-License-Identifier = "LicenseRef-GrabCAD-Terms"

[[annotations]]
path = ["pcb/resources/3d-models/grabcad/Mart_Berghs/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2020 Mart Berghs <https://grabcad.com/mart.berghs-1>"
SPDX-License-Identifier = "LicenseRef-GrabCAD-Terms"

[[annotations]]
path = ["pcb/resources/3d-models/grabcad/Mohamed_Owais/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 Mohamed Owais <https://grabcad.com/mohamed.owais-1>"
SPDX-License-Identifier = "LicenseRef-GrabCAD-Terms"

[[annotations]]
path = ["pcb/resources/3d-models/grabcad/Ni_Ni/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 ni_ni <https://grabcad.com/ni_ni-1>"
SPDX-License-Identifier = "LicenseRef-GrabCAD-Terms"

[[annotations]]
path = ["pcb/resources/3d-models/grabcad/Pablo_Queiroz/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 Pablo Queiroz <https://grabcad.com/pablo.queiroz-2>"
SPDX-License-Identifier = "LicenseRef-GrabCAD-Terms"

[[annotations]]
path = ["pcb/resources/3d-models/grabcad/Paul_Thelu/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 Paul THELU <https://grabcad.com/paul.thelu-2>"
SPDX-License-Identifier = "LicenseRef-GrabCAD-Terms"

[[annotations]]
path = ["pcb/resources/3d-models/grabcad/Stelian_Stefan/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Nicola Stelian Stefan <https://grabcad.com/nicola.stelian.stefan-4>"
SPDX-License-Identifier = "LicenseRef-GrabCAD-Terms"

[[annotations]]
path = ["pcb/resources/3d-models/grabcad/Nhatkhongbuon/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Nhatkhongbuon <https://grabcad.com/nhatkhongbuon-1>"
SPDX-License-Identifier = "LicenseRef-GrabCAD-Terms"

#
# Wago components are provided by UltraLibrarian, and are proprietary
#
[[annotations]]
path = ["pcb/resources/3d-models/wago/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 EMA Design Automation, Inc.  All Rights Reserved."
SPDX-License-Identifier = "LicenseRef-UltraLibrarian-Terms"
